### ISSUE TITLE
Kromme en mogelijk incorrecte zin in licentie

### ISSUE THREAD

**Issue by Kees-van-Beilen** [OpenTaal/opentaal-wordlist#10]
de zin: "Hierdoor is kunnen uw donaties via https://opentaal.org/vrienden-van-opentaal aftrekbaar zijn." is krom en mogelijk incorrect.

**Comment by PanderMusubi** [comment]
https://github.com/OpenTaal/opentaal-wordlist/commit/7164082cc80b06a9af3f6e9945354948f3761a52
