### ISSUE TITLE
Het woord 'burlen' mist een aantal vervoegingen

### ISSUE THREAD

**Issue by Sheepolution** [OpenTaal/opentaal-wordlist#13]
Zie https://woordenlijst.org/#/?q=burlen

Ik mis `burlt`, `burlden` en `geburld`.

**Comment by PanderMusubi** [comment]
Gefikst in 2.20.23 (die binnenkort wordt gepubliceerd). Zie ook https://woordinfo.org/ die ook update heeft gehad.
