### ISSUE TITLE
Licentie problemen

### ISSUE THREAD

**Issue by kroeckx** [OpenTaal/opentaal-wordlist#2]
De licentie vermeld nu:
```
Als u deze woordenlijst gebruikt bent u juridisch verplicht om de gegevens
hierboven te tonen in het colofon van u drukwerk of digitale product of dienst.
```

Dit lijkt een verandering te zijn van de licenties, met een nieuwe restricties. Deze restrictie is in mijn ogen niet aanvaardbaar. Beide licenties hebben verplichten van een vermelding van de auteur. Misschien is het de bedoeling om het proberen duidelijker te maken, maar het verandert de betekenis. Ik heb vooral een probleem met het woord "gebruik". Ik stel voor dat je gewoon heel de zin weg doet.

Bovendien is een van de licenties veranderd van CC-BY 3.0 naar CC-BY 4.0. In de vorige versie was er geen vermelding van "of later", en voor zover ik weet is er niet aan de houders van het auteursrecht gevraagd of die verandering aanvaardbaar is.

**Comment by PanderMusubi** [comment]
Dank voor je oplettendheid, we bespreken het vandaag en corrigeren het zo snel mogelijk.

**Comment by PanderMusubi** [comment]
@kroeckx kun je dubbelchecken of de BSD-licentie de correcte is, of het de two of three clause moet zijn? Dank alvast.

**Comment by kroeckx** [comment]
In de oude files stond een verwijzing naar:
- BSD (revised version): <http://creativecommons.org/licenses/BSD/deed.en>

En deze text:
BSD-license (revised version)
--------------------------------------------------------------------------------

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
* Neither the name of the OpenTaal, Simon Brouwer e.a., or Nederlandstalige Tex
Gebruikersgroep nor the names of its contributors may be used to endorse or
promote products derived from this software without specific prior written
permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by PanderMusubi** [comment]
Gefikst in https://github.com/OpenTaal/opentaal-wordlist/commit/26a1499f0fb6adaa90c7ade65f9994689f227e71 en https://github.com/OpenTaal/opentaal-wordlist/commit/f7f12b968438a95a37742f3bba62b3e78e15c884
